### ISSUE TITLE
Space+a is too sensitive

### ISSUE THREAD

**Issue by slidecuthelp** [r-plus/SlideCut#1]
When I am typing very fast I often select all and overwrite what I had already. This may be a difficult issue to fix but in the mean time can you please offer a preference pane that would allow me to turn off certain shortcuts?

If i would be able to turn off that shortcut in specific it would remove the issue since the letter A is commonly used by itself and followed/preceded by a space.

**Comment by blizzrdof77** [comment]
Agreed!

**Comment by r-plus** [comment]
Its issue need fundamental architecture fix.

**Comment by r-plus** [comment]
Still buggy.
