### ISSUE TITLE
Add support for pasting images with "space + v"

### ISSUE THREAD

**Issue by NguyenASang** [r-plus/SlideCut#6]
Hi, sorry for the delay.

## My Device
iPhone: 6
iOS: 12.5.5
Jailbreak: Chimera

## Future request
As I see it, this tweak _**only allows text**_ to be pasted when "space + v". Can you make it _**support images**_? Thanks in advance.

**Comment by r-plus** [comment]
ah, maybe possible.

**Comment by NguyenASang** [comment]
@r-plus Any updates on this ?

**Comment by r-plus** [comment]
I’m waiting iOS 15 jailbreak.

**Comment by NguyenASang** [comment]
> I’m waiting iOS 15 jailbreak.

Oh, I forgot :/

**Comment by NguyenASang** [comment]
@r-plus iOS 15 Jailbreak is out, I hope you still remember the promise.

**Comment by r-plus** [comment]
thanks for remind.

to support pasting image and others, changing to use native clipboard paste method is done.

v0.8 will be out when fix respring loop issue on Xina environment.

**Comment by NguyenASang** [comment]
I just installed v0.8 but it doesn't work 

Note: I tested this by copying the image in Photos and then trying to paste it in Notes

**Comment by NguyenASang** [comment]
@r-plus Hi, can you reproduce the bug ? Are you working on a fix ? 

Don't want to bother you, just want to make sure a bit.

**Comment by r-plus** [comment]
ah, just submitted fixed version v0.9 :)

happy new year!

2023年1月1日(日) 21:28 Nguyễn Anh Sáng ***@***.***>:

**Comment by NguyenASang** [comment]
Thank you very much. 

Happy new year ! May you have a prosperous new year.

**Comment by NguyenASang** [comment]
Latest version works perfectly :)
